"""Localized UI strings for 11 CONVERTER."""

STRINGS = {
    "en": {
        "window_title": "11 CONVERTER",
        "title_bar_files_word": "files",
        "nav_music": "Music",
        "nav_history": "History",
        "nav_settings": "Settings",
        "sidebar_tagline": "Audio converter",
        "page_main_title": "Convert",
        "page_subtitle": "Batch export audio locally — drag files in, pick a format, export.",
        "url_placeholder": "Paste file paths (one per line), or leave empty and click Add",
        "queue_label": "Track queue",
        "col_title": "Title",
        "col_artist": "Artist",
        "col_album": "Album",
        "col_format": "Format",
        "col_bpm": "BPM",
        "col_dur": "Duration",
        "col_file_date": "File date",
        "col_file": "File",
        "col_logged": "Logged",
        "queue_empty": "No tracks loaded",
        "queue_add_tracks": "Add",
        "btn_add_paths": "Add",
        "dlg_pick_tracks_title": "Choose files for the queue",
        "dlg_pick_tracks_hint": "Uncheck files you do not want to load (they will not be converted).",
        "btn_load_selected": "Load selected",
        "btn_select_all_tracks": "Select all",
        "btn_select_none_tracks": "Clear selection",
        "msg_pick_at_least_one": "Select at least one file.",
        "dlg_cancel": "Cancel",
        "drag_hint": "Drop files here, or click Add",
        "drag_hint_sub": "MP3, WAV, FLAC, AIFF, M4A, and more",
        "badge_none": "No files · 0.0 MB",
        "badge_files": "{n} files · {kinds} · {size}",
        "sidebar_source_prefix": "Source files",
        "sidebar_export_prefix": "Export format",
        "sidebar_no_source_yet": "—",
        "progress_ready": "Ready",
        "btn_convert": "Convert",
        "btn_converting": "Converting…",
        "output_format": "Output Format",
        "output_folder": "Output Folder",
        "more_settings": "More settings",
        "history_title": "Track history",
        "history_sub": "Every file you load is logged here for quick reference.",
        "history_clear": "Clear history",
        "history_clear_confirm": "Delete all history entries? This cannot be undone.",
        "history_empty": "No history yet. Load audio files on the Music page.",
        "history_col_open": "Open",
        "history_open_btn": "Open",
        "history_file_missing": "File not found or was moved — it cannot be opened.",
        "history_file_unsafe": "This file did not pass the safety check (header). It will not be opened.",
        "history_open_failed": "Could not open file:\n{e}",
        "settings_main": "Settings",
        "settings_lang": "Language",
        "settings_lang_hint": "Interface language — Hebrew or English.",
        "settings_appearance": "Appearance",
        "settings_appearance_hint": "Light or dark theme. Saved automatically.",
        "settings_audio_section": "Audio resolution & export",
        "settings_audio_hint": "Sample rate, bit depth (WAV/AIFF), MP3 320 kbps CBR, metadata, naming. Saved automatically.",
        "label_sample_rate": "Sample rate",
        "sr_44100": "44100 Hz — music (CD)",
        "sr_48000": "48000 Hz — video workflows",
        "sr_96000": "96000 Hz — high-res studio",
        "label_bit_depth": "Bit depth (WAV / AIFF)",
        "bd_16": "16-bit (CD)",
        "bd_24": "24-bit (studio)",
        "bd_32f": "32-bit float (headroom)",
        "mp3_quality_note": "MP3: 320 kbps CBR (constant bitrate) — best for DJ software BPM analysis.",
        "aac_quality_note": "M4A AAC: fixed bitrate (CBR-style) for stable BPM detection.",
        "settings_embed_meta": "Write ID3/metadata (title, artist, album, BPM, key) to exports",
        "settings_normalize": "Normalize loudness before export (helps quiet sources)",
        "settings_name_pattern": "Exported file names",
        "settings_name_pattern_simple": "Choose up to four fields and a separator — no curly braces needed.",
        "settings_formats_title": "Output formats (quick guide)",
        "fmt_wav": "WAV — Uncompressed; best for editing and mastering; large files.",
        "fmt_mp3": "MP3 — Small; plays everywhere; lossy (not ideal for re-editing).",
        "fmt_flac": "FLAC — Lossless compression; smaller than WAV; great for archiving.",
        "fmt_aiff": "AIFF — Like WAV; common on Mac / pro audio; large files.",
        "fmt_m4a": "M4A (AAC) — Compact; strong quality/size balance; great for phones.",
        "pattern_preview_label": "Preview",
        "pattern_slot_prefix": "Part",
        "pattern_sep_label": "Between parts",
        "pattern_advanced": "Edit pattern as text (advanced)",
        "pat_skip": "— skip —",
        "pat_artist": "Artist",
        "pat_title": "Title",
        "pat_album": "Album",
        "pat_bpm": "BPM",
        "pat_key": "Key",
        "settings_name_pattern_hint": "Placeholders: {artist} {title} {album} {bpm} {key} — e.g. [ {bpm} ] {artist} - {title}",
        "settings_split_format": "Save each format in its own subfolder (WAV, MP3, …)",
        "settings_video_extract": "Allow loading video files (MP4, MKV, …) — audio track is decoded",
        "settings_video_hint": "“Extract original” lossless copy requires ffmpeg; otherwise audio is re-encoded per settings above.",
        "btn_back": "← Back",
        "theme_light": "☀ Light",
        "theme_dark": "🌙 Dark",
        "lang_pick_he": "עברית",
        "lang_pick_en": "English",
        "dlg_select_audio": "Select audio files",
        "dlg_audio_types": "Audio",
        "dlg_pick_parent": "Choose parent folder for output (e.g. Desktop)",
        "dlg_output_name": "Output folder name",
        "dlg_output_prompt": "Name for the new folder that will hold converted files:",
        "dlg_mkdir_err": "Could not create folder:\n{e}",
        "msg_warn_paths": "No valid audio file paths found. Paste full paths (one per line) or leave empty and use +.",
        "msg_invalid_files_all": "None of the files passed the safety check (real media headers). Only genuine audio/video files are accepted.",
        "msg_drop_nothing_found": "No supported audio files in the drop. Drop files or a folder that contains them (subfolders included).",
        "msg_warn_convert": "Add audio files and set an output folder first.",
        "msg_ffmpeg_missing": (
            "11 CONVERTER could not find FFmpeg, which it needs to read and encode audio.\n\n"
            "Reinstall the app (the installer includes FFmpeg), or install FFmpeg and add it to PATH."
        ),
        "msg_coming": "{title} — coming soon.",
        "browse_folder": "Browse",
        "format_help_title": "Output formats — quick guide",
        "format_help_body": (
            "WAV — Uncompressed PCM: best fidelity for editing and mastering; files are large.\n"
            "MP3 — Lossy compression: small files, plays everywhere; ideal for sharing and casual listening.\n"
            "FLAC — Lossless compression: full quality like WAV in a smaller file; great for archiving.\n"
            "AIFF — Uncompressed like WAV; common in Mac / pro audio pipelines.\n"
            "M4A (AAC) — Efficient compressed format; strong quality/size balance, especially on Apple devices."
        ),
        "settings_formats_heading": "Output formats",
        "help_audio_export_title": "Audio export — details",
        "help_pattern_title": "File naming — details",
        "help_video_title": "Video import — details",
        "help_lang_title": "Language",
        "help_appearance_title": "Appearance",
        "progress_processing": "Processing {i} / {total}",
        "progress_active": "{done}/{total} songs · {done_pct}% done · {rem_pct}% left",
        "progress_done": "100% done · 0% left",
        "progress_ready_line": "Ready · 0% done · 100% pending · {n} in queue",
        "progress_ready_line_empty": "Ready · load songs in the queue above",
        "eta": "ETA:",
        "eta_calc": "Calculating…",
        "file_kind_unknown": "Unknown",
        "msg_none_marked_convert": "No files are marked for conversion. Turn on the checkbox next to tracks you want to convert.",
        "queue_hdr_convert": "✓",
        "queue_hdr_remove": "×",
    },
    "he": {
        "window_title": "11 CONVERTER",
        "title_bar_files_word": "קבצים",
        "nav_music": "מוזיקה",
        "nav_history": "היסטוריה",
        "nav_settings": "הגדרות",
        "sidebar_tagline": "ממיר אודיו",
        "page_main_title": "המרה",
        "page_subtitle": "ייצוא אודיו מקומי — גרור קבצים, בחר פורמט, ייצא.",
        "url_placeholder": "הדבק נתיבי קבצים (שורה לכל קובץ), או השאר ריק ולחץ הוסף",
        "queue_label": "תור רצועות",
        "col_title": "שם",
        "col_artist": "אמן",
        "col_album": "אלבום",
        "col_format": "פורמט",
        "col_bpm": "BPM",
        "col_dur": "משך",
        "col_file_date": "תאריך קובץ",
        "col_file": "קובץ",
        "col_logged": "נרשם",
        "queue_empty": "אין רצועות בטעינה",
        "queue_add_tracks": "הוסף",
        "btn_add_paths": "הוסף",
        "dlg_pick_tracks_title": "בחירת קבצים לתור",
        "dlg_pick_tracks_hint": "בטל סימון לקבצים שלא ייכנסו לתור (לא יומרו).",
        "btn_load_selected": "טען נבחרים",
        "btn_select_all_tracks": "בחר הכל",
        "btn_select_none_tracks": "בטל סימון",
        "msg_pick_at_least_one": "סמן לפחות קובץ אחד.",
        "dlg_cancel": "ביטול",
        "drag_hint": "גרור קבצים לכאן, או לחץ הוסף",
        "drag_hint_sub": "MP3, WAV, FLAC, AIFF, M4A ועוד",
        "badge_none": "אין קבצים · 0.0 MB",
        "badge_files": "{n} קבצים · {kinds} · {size}",
        "sidebar_source_prefix": "קבצים בתור",
        "sidebar_export_prefix": "פורמט יצוא",
        "sidebar_no_source_yet": "—",
        "progress_ready": "מוכן",
        "btn_convert": "המר",
        "btn_converting": "ממיר…",
        "output_format": "פורמט פלט",
        "output_folder": "תיקיית פלט",
        "more_settings": "הגדרות נוספות",
        "history_title": "היסטוריית רצועות",
        "history_sub": "כל קובץ שתטען יירשם כאן לגישה מהירה.",
        "history_clear": "נקה היסטוריה",
        "history_clear_confirm": "למחוק את כל ההיסטוריה? אי אפשר לשחזר.",
        "history_empty": "אין היסטוריה עדיין. טען קבצי אודיו בעמוד המוזיקה.",
        "history_col_open": "פתיחה",
        "history_open_btn": "פתח",
        "history_file_missing": "הקובץ לא נמצא או הוזז — לא ניתן לפתוח.",
        "history_file_unsafe": "הקובץ לא עבר את בדיקת הבטיחות (כותרת/חתימה). לא ייפתח.",
        "history_open_failed": "לא ניתן לפתוח את הקובץ:\n{e}",
        "settings_main": "הגדרות",
        "settings_lang": "שפה",
        "settings_lang_hint": "שפת הממשק — עברית או אנגלית.",
        "settings_appearance": "מראה",
        "settings_appearance_hint": "מצב בהיר או כהה. נשמר אוטומטית.",
        "settings_audio_section": "איכות שמע וייצוא",
        "settings_audio_hint": "תדר דגימה, עומק ביט (WAV/AIFF), MP3 ‏320 CBR, מטא־דאטה, שמות קבצים. נשמר אוטומטית.",
        "label_sample_rate": "תדר דגימה",
        "sr_44100": "44100 Hz — מוזיקה (CD)",
        "sr_48000": "48000 Hz — וידאו / פוסט",
        "sr_96000": "96000 Hz — אולפן ברזולוציה גבוהה",
        "label_bit_depth": "עומק ביט (WAV / AIFF)",
        "bd_16": "16-bit (CD)",
        "bd_24": "24-bit (אולפן)",
        "bd_32f": "32-bit float (מניעת clipping)",
        "mp3_quality_note": "MP3: ‏320 kbps CBR — מתאים לניתוח BPM בתוכנות DJ.",
        "aac_quality_note": "M4A AAC: קצב קבוע — יציב ל־BPM.",
        "settings_embed_meta": "כתיבת מטא־דאטה (שם, אמן, אלבום, BPM, סולם) לקבצי הפלט",
        "settings_normalize": "נרמול עוצמה לפני ייצוא (מקורות חלשים)",
        "settings_name_pattern": "שמות קבצים בייצוא",
        "settings_name_pattern_simple": "עד ארבעה שדות ומפריד — בלי סוגריים מסולסלים.",
        "settings_formats_title": "פורמטי פלט (מדריך קצר)",
        "fmt_wav": "WAV — ללא דחיסה; מצוין לעריכה ומאסטרינג; קבצים גדולים.",
        "fmt_mp3": "MP3 — קטן ונתמך בכל מקום; אובדן איכות (פחות לעריכה חוזרת).",
        "fmt_flac": "FLAC — ללא אובדן עם דחיסה; קטן מ־WAV; מצוין לארכיון.",
        "fmt_aiff": "AIFF — כמו WAV; נפוץ ב־Mac / אודיו מקצועי; קבצים גדולים.",
        "fmt_m4a": "M4A (AAC) — קומפקטי; איזון טוב; מצוין לטלפון ושיתוף.",
        "pattern_preview_label": "תצוגה מקדימה",
        "pattern_slot_prefix": "חלק",
        "pattern_sep_label": "בין חלקים",
        "pattern_advanced": "עריכת תבנית כטקסט (מתקדם)",
        "pat_skip": "— דלג —",
        "pat_artist": "אמן",
        "pat_title": "כותרת",
        "pat_album": "אלבום",
        "pat_bpm": "BPM",
        "pat_key": "סולם (Key)",
        "settings_name_pattern_hint": "משתנים: {artist} {title} {album} {bpm} {key} — לדוגמה: [ {bpm} ] {artist} - {title}",
        "settings_split_format": "תיקיית משנה לכל פורמט (WAV, MP3…)",
        "settings_video_extract": "טעינת קבצי וידאו (MP4, MKV…) — יוצאים מהמסלול האודיו",
        "settings_video_hint": "חילוץ ללא המרה דורש ffmpeg; אחרת האודיו מקודד מחדש לפי ההגדרות.",
        "btn_back": "← חזרה",
        "theme_light": "☀ בהיר",
        "theme_dark": "🌙 כהה",
        "lang_pick_he": "עברית",
        "lang_pick_en": "English",
        "dlg_select_audio": "בחירת קבצי אודיו",
        "dlg_audio_types": "אודיו",
        "dlg_pick_parent": "בחר תיקיית הורה לפלט (למשל שולחן עבודה)",
        "dlg_output_name": "שם תיקיית הפלט",
        "dlg_output_prompt": "שם לתיקייה שבה יישמרו הקבצים המומרים:",
        "dlg_mkdir_err": "לא ניתן ליצור את התיקייה:\n{e}",
        "msg_warn_paths": "לא נמצאו נתיבי קבצים תקינים. הדבק נתיבים מלאים (שורה לכל קובץ) או השאר ריק ולחץ +.",
        "msg_invalid_files_all": "אף קובץ לא עבר את בדיקת הבטיחות (כותרות מדיה אמיתיות). מתקבלים רק קבצי אודיו/וידאו אמיתיים.",
        "msg_drop_nothing_found": "לא נמצאו קבצי אודיו נתמכים. גרור קבצים או תיקייה שמכילה אותם (כולל תת־תיקיות).",
        "msg_warn_convert": "הוסף קבצי אודיו והגדר תיקיית פלט קודם.",
        "msg_ffmpeg_missing": (
            "11 CONVERTER לא מצא את FFmpeg, שנחוץ לקריאה ולקידוד של אודיו.\n\n"
            "התקן מחדש את האפליקציה (ה-installer כולל FFmpeg), או התקן FFmpeg והוסף אותו ל-PATH."
        ),
        "msg_coming": "{title} — בקרוב.",
        "browse_folder": "בחר תיקייה",
        "format_help_title": "פורמטי פלט — הסבר קצר",
        "format_help_body": (
            "WAV — PCM ללא דחיסה: הכי טוב לעריכה ומאסטרינג; קבצים גדולים.\n"
            "MP3 — דחיסה עם אובדן: קבצים קטנים ונגן בכל מקום; מתאים לשיתוף והאזנה יומיומית.\n"
            "FLAC — דחיסה ללא אובדן: איכות מלאה כמו WAV בקובץ קטן יותר; מצוין לארכיון.\n"
            "AIFF — ללא דחיסה כמו WAV; נפוץ בזרימות Mac / אולפן.\n"
            "M4A (AAC) — דחיסה יעילה; איזון טוב בין איכות לגודל, במיוחד במכשירי Apple."
        ),
        "settings_formats_heading": "פורמטי פלט",
        "help_audio_export_title": "איכות שמע וייצוא — פרטים",
        "help_pattern_title": "שמות קבצים — פרטים",
        "help_video_title": "ייבוא וידאו — פרטים",
        "help_lang_title": "שפה",
        "help_appearance_title": "מראה",
        "progress_processing": "מעבד {i} מתוך {total}",
        "progress_active": "{done}/{total} שירים · {done_pct}% בוצעו · {rem_pct}% נותרו",
        "progress_done": "100% הושלם · 0% נותרו",
        "progress_ready_line": "מוכן · 0% בוצעו · 100% ממתינים · {n} בתור",
        "progress_ready_line_empty": "מוכן · טען שירים באזור למעלה",
        "eta": "זמן משוער:",
        "eta_calc": "מחשב…",
        "file_kind_unknown": "לא ידוע",
        "msg_none_marked_convert": "אין קבצים מסומנים להמרה. סמן את תיבת הכלול ליד הרצועות שברצונך להמיר.",
        "queue_hdr_convert": "✓",
        "queue_hdr_remove": "×",
    },
}
